/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalaryRoiRouteImport } from './routes/salary-roi'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiYahooStreamRouteImport } from './routes/api.yahoo-stream'
import { Route as ApiSecRouteImport } from './routes/api.sec'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as ApiNewsRouteImport } from './routes/api.news'
import { Route as ApiMarketRouteImport } from './routes/api.market'
import { Route as ApiInstrumentRouteImport } from './routes/api.instrument'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryRoiRoute = SalaryRoiRouteImport.update({
  id: '/salary-roi',
  path: '/salary-roi',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYahooStreamRoute = ApiYahooStreamRouteImport.update({
  id: '/api/yahoo-stream',
  path: '/api/yahoo-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecRoute = ApiSecRouteImport.update({
  id: '/api/sec',
  path: '/api/sec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketRoute = ApiMarketRouteImport.update({
  id: '/api/market',
  path: '/api/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstrumentRoute = ApiInstrumentRouteImport.update({
  id: '/api/instrument',
  path: '/api/instrument',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/docs': typeof DocsRoute
  '/salary-roi': typeof SalaryRoiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/instrument': typeof ApiInstrumentRoute
  '/api/market': typeof ApiMarketRoute
  '/api/news': typeof ApiNewsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sec': typeof ApiSecRoute
  '/api/yahoo-stream': typeof ApiYahooStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/docs': typeof DocsRoute
  '/salary-roi': typeof SalaryRoiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/instrument': typeof ApiInstrumentRoute
  '/api/market': typeof ApiMarketRoute
  '/api/news': typeof ApiNewsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sec': typeof ApiSecRoute
  '/api/yahoo-stream': typeof ApiYahooStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/docs': typeof DocsRoute
  '/salary-roi': typeof SalaryRoiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/instrument': typeof ApiInstrumentRoute
  '/api/market': typeof ApiMarketRoute
  '/api/news': typeof ApiNewsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sec': typeof ApiSecRoute
  '/api/yahoo-stream': typeof ApiYahooStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/docs'
    | '/salary-roi'
    | '/sitemap.xml'
    | '/api/instrument'
    | '/api/market'
    | '/api/news'
    | '/api/search'
    | '/api/sec'
    | '/api/yahoo-stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/docs'
    | '/salary-roi'
    | '/sitemap.xml'
    | '/api/instrument'
    | '/api/market'
    | '/api/news'
    | '/api/search'
    | '/api/sec'
    | '/api/yahoo-stream'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/docs'
    | '/salary-roi'
    | '/sitemap.xml'
    | '/api/instrument'
    | '/api/market'
    | '/api/news'
    | '/api/search'
    | '/api/sec'
    | '/api/yahoo-stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  DocsRoute: typeof DocsRoute
  SalaryRoiRoute: typeof SalaryRoiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiInstrumentRoute: typeof ApiInstrumentRoute
  ApiMarketRoute: typeof ApiMarketRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSecRoute: typeof ApiSecRoute
  ApiYahooStreamRoute: typeof ApiYahooStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-roi': {
      id: '/salary-roi'
      path: '/salary-roi'
      fullPath: '/salary-roi'
      preLoaderRoute: typeof SalaryRoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yahoo-stream': {
      id: '/api/yahoo-stream'
      path: '/api/yahoo-stream'
      fullPath: '/api/yahoo-stream'
      preLoaderRoute: typeof ApiYahooStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sec': {
      id: '/api/sec'
      path: '/api/sec'
      fullPath: '/api/sec'
      preLoaderRoute: typeof ApiSecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market': {
      id: '/api/market'
      path: '/api/market'
      fullPath: '/api/market'
      preLoaderRoute: typeof ApiMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instrument': {
      id: '/api/instrument'
      path: '/api/instrument'
      fullPath: '/api/instrument'
      preLoaderRoute: typeof ApiInstrumentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  DocsRoute: DocsRoute,
  SalaryRoiRoute: SalaryRoiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiInstrumentRoute: ApiInstrumentRoute,
  ApiMarketRoute: ApiMarketRoute,
  ApiNewsRoute: ApiNewsRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSecRoute: ApiSecRoute,
  ApiYahooStreamRoute: ApiYahooStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
